require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayStyleGuide: true
  Exclude:
    - '.git/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/**/*'

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/EmptyMethod:
  EnforcedStyle: expanded

# TODO: Remove following

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
