development:
  posting_to_twitter_enabled: true
  sign_in_enabled: true

test:
  posting_to_twitter_enabled: true
  sign_in_enabled: true

production:
  posting_to_twitter_enabled: <%= ENV['POSTING_TO_TWITTER_ENABLED'] %>
  sign_in_enabled: <%= ENV['SIGN_IN_ENABLED'] %>
