development:
  posting_to_twitter_enabled: true
  sign_in_enabled: true
  admin_twitter_ids:
    - '9436992'
    - '18548072'

test:
  posting_to_twitter_enabled: true
  sign_in_enabled: true
  admin_twitter_ids:
    - '9436992'
    - '18548072'

production:
  posting_to_twitter_enabled: <%= ENV['POSTING_TO_TWITTER_ENABLED'] %>
  sign_in_enabled: <%= ENV['SIGN_IN_ENABLED'] %>
  admin_twitter_ids: <%= (ENV['ADMIN_TWITTER_IDS'] || '').split(',') %>
